### ISSUE TITLE
Is this repo taking part in hacktoberfest?

### ISSUE THREAD

**Issue by Kunal7069** [Vijaykv5/Image-Searcher#10]
Is contribution in this repo will be counted in hacktoberfest 2023?

**Comment by Vijaykv5** [comment]
Yes @Kunal7069

**Comment by Kunal7069** [comment]
@Vijaykv5 Sir I want to add a feature in this project 
How's the idea if we give the user a option to save the photos he/she likes.
For this we need to first create login signup page so that each user can access his/her saved photos and then work on this feature to save photos using the url of photo which is provided by the unsplash api.

**Comment by Vijaykv5** [comment]
Yeah I appreciate your idea. But before Signin/Signup that as you said, there can a Heart(like) button where users can click on it and the respective photo is moved onto a section called liked in navbar? How it would be?

**Comment by Kunal7069** [comment]
But if in future he/she want to come back and see his liked photos then to do this we need to create login signup

**Comment by Kunal7069** [comment]
@Vijaykv5 login signup will help to keep record of liked photos.

**Comment by Vijaykv5** [comment]
> @Vijaykv5 login signup will help to keep record of liked photos.

Yeah but We can keep aside it later. First is to add a like button on every image

**Comment by Kunal7069** [comment]
@Vijaykv5 So can I work on this feature?

**Comment by Vijaykv5** [comment]
> > @Vijaykv5 login signup will help to keep record of liked photos.
> 
> Yeah but We can keep aside it later. First is to add a like button on every image

@Kunal7069 you can work on this.. Not on Login/signup page

**Comment by Kunal7069** [comment]
@Vijaykv5 Ok I will be starting working on it.
And I want to know that after what date if I made contribution So it will be considered a merged pull request for hacktoberfest 23?

**Comment by Vijaykv5** [comment]
I'll register this project on sept 26  and you can raise PR Between October 1 and October 31 as per Hacktober fest guideline.

**Comment by Vijaykv5** [comment]
@Kunal7069 Please make sure to add the feature as a new issue and work on it ...Because I'll be closing this issue and I'll assign you in that issue.

**Comment by Kunal7069** [comment]
@Vijaykv5 Ok sir then on 29 or 30 September I will be raising the issue for this feature.
Is it fine?

**Comment by Vijaykv5** [comment]
Ok @Kunal7069
