### ISSUE TITLE
Github Link

### ISSUE THREAD

**Issue by Vijaykv5** [Vijaykv5/Image-Searcher#11]
How about adding an github link here :
<img width="1440" alt="Screenshot 2023-09-22 at 9 53 50 AM" src="https://github.com/Vijaykv5/Image-Searcher/assets/94985341/454eb7a1-60ee-495d-a987-58783f2b5955">

**Comment by JTateCC** [comment]
Happy to contribute to this.

**Comment by Vijaykv5** [comment]
I've assigned you the task

**Comment by Myworld21** [comment]
This project is looking awesome. I am interested in working on this project. Can you please assign it to me also. I'll love to work on this. Thank You!

**Comment by Vijaykv5** [comment]
> This project is looking awesome. I am interested in working on this project. Can you please assign it to me also. I'll love to work on this. Thank You!

You can work on it :)
