### ISSUE TITLE
[OTHER] Add the Hacktoberfest Topic to Repository!

### ISSUE THREAD

**Issue by lcrojano** [Vijaykv5/Image-Searcher#15]
Hi!
Just a quick reminder! If you haven't already, please add the "**hacktoberfest**" tag to our repository to boost our project's visibility during Hacktoberfest.

Here's how you can do it:

Go to the Settings page for our repository.
Click on the "Topics" tab on the left-hand side.
In the "Add topics" field, type "hacktoberfest."
Click the "Add topic" button.

That's it! By adding the Hacktoberfest topic, we can increase the visibility of our project and attract more contributors eager to participate in the event.

Thank you for your support !

Best regards,

**Comment by Vijaykv5** [comment]
@lcrojano The Tag for hacktoberfest is not still live
