### ISSUE TITLE
[BUG] <Correct Banner Image is not displayed if the keyword input is changed>

### ISSUE THREAD

**Issue by Sanidhya0077** [Vijaykv5/Image-Searcher#16]
**Description**
Considering a usecase if a keyword 'Phones' from selection menu is chosen and then replaced with 'World Map' .

**Expected Behavior**

The banner image should be disappeared

**Actual Behavior**

The banner Image with "Phone" still displayed.

**Screenshots (if applicable)**

**Additional Information**

Add any other context or information about the issue here.

**Comment by Vijaykv5** [comment]
Are u interested in working on it? @Sanidhya0077

**Comment by lsink** [comment]
I would like to take this if @Sanidhya0077 is not working on it. The fix should also get rid of the empty space when searching by input field instead of clicking a button below it.

**Comment by Sanidhya0077** [comment]
> I would like to take this if @Sanidhya0077 is not working on it. The fix should also get rid of the empty space when searching by input field instead of clicking a button below it.

**Comment by Sanidhya0077** [comment]
@Vijaykv5  I am working on it will give an update soon.

**Comment by Vijaykv5** [comment]
@Sanidhya0077 Hey how it's going so far... its being 5 days now 
Ready for a PR?

**Comment by Sanidhya0077** [comment]
@Vijaykv5 , give me some time will give an update today for sure.

**Comment by lsink** [comment]
@Vijaykv5 This fix is hiding the banner image but still showing banner text behind the search results. You can see this if you click one of the links and then do a search.
