### ISSUE TITLE
[FEATURE] Download Button on Each Card

### ISSUE THREAD

**Issue by veerprakash28** [Vijaykv5/Image-Searcher#21]
**Description**

Add a download button on each card, when a user hovers on it.

**Expected Behavior**

When the user hovers on the card, then a download button will be shown at the top right and on clicking that button, the Image will be downloaded in the system directly

**Actual Behavior**

Right Now, there is no way to download the actual image, and if we open the image in new tab, then the resolution of the image is lower

**Comment by Vijaykv5** [comment]
That's a good idea ..hOWEVER WE ARE WORKING ON A LIKE BUTTON ON TOP RIGHT 

I think its good to add the download button appear at the center while hovering on it. What you think?

**Comment by B1TSH3LL** [comment]
i think i should work on this , i can create an animation for the required behavior for the button. and you can just import and use anywhere as you want.

Please Assign This To Me.

**Comment by veerprakash28** [comment]
Yeah sure! that works too. When the download button is there the background will be blurred for making the UI look better. I can work on this.

**Comment by Vijaykv5** [comment]
@B1TSH3LL we will be following first come first serve... Since @veerprakash28 Opened up this issue and wants to work on it, I'm assigning him this now

You may can explore any other issues 🙂

**Comment by jaypatel523** [comment]
I have implemented this feature. But i don't know how to contribute ? Help me 

## Demo 
![download-image](https://github.com/Vijaykv5/Image-Searcher/assets/97498433/ebdee499-d7c3-4f6b-9f05-551842e0ed21)

**Comment by Vijaykv5** [comment]
@veerprakash28  I think someone have opened Up the PR Directly on this ...Are you still working on or else I need to close the issue

**Comment by jaypatel523** [comment]
Fine by me. Next time i'll take care of it.

**Comment by Vijaykv5** [comment]
@veerprakash28 I'm Merging @jaypatel523 PR now... you may check on other Issues

**Comment by veerprakash28** [comment]
Hey, I was working on this and it was almost completed. Anyways I'll look for another issues.
