### ISSUE TITLE
No Initial Scrolling 

### ISSUE THREAD

**Issue by jaypatel523** [Vijaykv5/Image-Searcher#29]
## Description

The page scrolls initially when user visits it for the first time, and a back-to-top button is also there.
The page should show random images in the beginning.

**Comment by Vijaykv5** [comment]
Could you elaborate the issue... I couldn't get it

**Comment by jaypatel523** [comment]
- When we visit the site then there is scrolling effect even if there are no images.
- The UI looks better it we put random images in this.

https://github.com/Vijaykv5/Image-Searcher/assets/97498433/ba396e94-dc5c-4738-a853-44a4f29e3ab0

**Comment by Vijaykv5** [comment]
Ok I guess we can have it like no Scrolling at first rather than adding a random image @jaypatel523 

When initially user goes into the website there is not scrolling effect.

**Comment by Vijaykv5** [comment]
Let me know if @jaypatel523 wants to work on it

**Comment by jaypatel523** [comment]
I want to work on it. Also Initially if there are some random images then it looks better than empty page.

**Comment by Vijaykv5** [comment]
> I want to work on it. Also Initially if there are some random images then it looks better than empty page.

No at first user visits the webpage it should be clean with only header , searchbar and tags.. No need for any other image

**Comment by jaypatel523** [comment]
Fine. Please let me fix this bug.

**Comment by jaypatel523** [comment]
I fixed the bug. Can i make pull request now ?

**Comment by Vijaykv5** [comment]
Sure Make sure to an demo also attached with your PR

**Comment by Vijaykv5** [comment]
@jaypatel523 Make sure add a git pull before you add PR

**Comment by jaypatel523** [comment]
I have make the pull request. By the way, I'm complete beginner in open source contribution so forgive me for my mistakes.

**Comment by Vijaykv5** [comment]
I merged it @jaypatel523 Thank you :)
