### ISSUE TITLE
[DOCS] The logo is decentralized at documentation

### ISSUE THREAD

**Issue by juninhokaponne** [Vijaykv5/Image-Searcher#32]
**Description**

The logo is decentralized at documentation !

What should happen?

The logo should stay centralized.

**Screenshots (if applicable)**

![image](https://github.com/Vijaykv5/Image-Searcher/assets/49099875/54eb49ba-1c97-4190-8648-9f968673ed1c)

**Additional Information**

I can open Open a new feature to fix/improve it.

**Comment by Rajdeep1311** [comment]
Sir I solved the issue and raised a PR but for some reason the checks are failing, can please check and tell me why?
