### ISSUE TITLE
[BUG] Downloaded images are of low quality

### ISSUE THREAD

**Issue by veerprakash28** [Vijaykv5/Image-Searcher#35]
**Description**

The download image is of low quality

**Expected Behavior**

The quality of image should be high when it is downloaded.

**Actual Behavior**

Image is of low quality

**Additional Information**

I have fixed this issue on local, let me know if I should raise the PR or not, Also made the code and UI better.

**Screenshots**
Left: High Quality | Right: Low Quality

<img width="1440" alt="Screenshot 2023-09-30 at 2 06 14 PM" src="https://github.com/Vijaykv5/Image-Searcher/assets/94482800/d83fd717-5322-4696-9934-16d82e2f541e">

**Comment by Vijaykv5** [comment]
Let me know how you enhanced it ...I mean the steps @veerprakash28

**Comment by veerprakash28** [comment]
- Changed the small quality download link to full
- Added icon for download instead of text
- Made separated component for the images card
- Added downloaded image link so that downlaoded image name will look like this: Image-searcher-(random8digitNumber)

**Comment by Vijaykv5** [comment]
If you're done please add a PR to it 

> * Changed the small quality download link to full
> * Added icon for download instead of text
> * Made separated component for the images card
> * Added downloaded image link so that downlaoded image name will look like this: Image-searcher-(random8digitNumber)

**Comment by veerprakash28** [comment]
Sure, I'll raise a PR
