### ISSUE TITLE
Improvement for Next functionality

### ISSUE THREAD

**Issue by aanchal-fatwani** [Vijaykv5/Image-Searcher#45]
@Vijaykv5  As part of HacktoberFest2023, I wish to enhance the functionality of the Next tab for better UX. The Next tab should bring the focus of the user to the start of the image display.
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

**Comment by Vijaykv5** [comment]
@aanchal-fatwani  I didn't completely got your thoughts. May you can add it precisely by adding a screenshot or example

**Comment by aanchal-fatwani** [comment]
Hi @Vijaykv5, on clicking of Next button the user still sees the end of current page result set. Ideally, on clicking of next button, the start of the new results should be on user's view port, i.e. the page should be scrolled to top of results and not be at end of results.

**Comment by Vijaykv5** [comment]
cool. Go for it! @aanchal-fatwani

**Comment by Vijaykv5** [comment]
@aanchal-fatwani I think what we can do it like #59 ?

**Comment by Vijaykv5** [comment]
Like we can remove the next and prev buttons and we can implement a infinite scroll?

**Comment by aanchal-fatwani** [comment]
@Vijaykv5 I have already added the fix for the current issue. Should I proceed with the implementation of Infinite Scroll?

**Comment by Vijaykv5** [comment]
@aanchal-fatwani yeah please Proceed with the implementation of Infinite scroll

**Comment by Vijaykv5** [comment]
Nope #59  he wants to do that 

Anyway I'll be merging this PR, later we will implement Infinite scrolling
