### ISSUE TITLE
Grammatical enhancements

### ISSUE THREAD

**Issue by aanchal-fatwani** [Vijaykv5/Image-Searcher#46]
@Vijaykv5 As part of HacktoberFest2023, I wish to fix and add grammatical enhancements to the content of links. This would help achieve better User Experience.
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

![image](https://github.com/Vijaykv5/Image-Searcher/assets/63228776/9830117b-46cd-43d4-b48d-92a58a037868)

**Comment by Vijaykv5** [comment]
Cool go for it
