### ISSUE TITLE
[DOCS] Enhance README with Contributors Section

### ISSUE THREAD

**Issue by rubemfsv** [Vijaykv5/Image-Searcher#50]
**Description**

The README file serves as a crucial source of information for our project. To foster transparency and acknowledge the valuable contributions from our team members and collaborators, we should add a dedicated "Contributors" section to the README. This small but meaningful addition reflects our commitment to open collaboration and transparency.

**Expected Behavior**

To have a final section in the README with contributors. 

**Actual Behavior**

Nowadays, it shows about contributing and doesn't show about the contributors. It would be good to show the people who helped with the project.

**Screenshots (if applicable)**

N/A

**Additional Information**

N/A

**Comment by rubemfsv** [comment]
Please, assign to me if possible.

**Comment by rubemfsv** [comment]
I resolved here https://github.com/Vijaykv5/Image-Searcher/pull/51

**Comment by Vijaykv5** [comment]
Cool Thanks for your contribution 🚀
