### ISSUE TITLE
[OTHER] Horizontal scrollbar for topics dosen't look good

### ISSUE THREAD

**Issue by accodes21** [Vijaykv5/Image-Searcher#52]
**Description**

The horizontal scroll bar for the topics doesn't look good in the UI. It looks kind of awkward for the medium to large screens.

**Expected Behavior**

It should not be present for large devices as it hampers the smooth UI of the project.

**Actual Behavior**

It is right there in the center of the UI making, distracting the user from the rest of the website.

**Screenshots (if applicable)**

![Screenshot (385)](https://github.com/Vijaykv5/Image-Searcher/assets/101868279/dfcbba24-a451-4473-b9f6-2b3b27084c73)

**Additional Information**

It should be removed for large devices so as to make the UI smooth and attractive

**Comment by accodes21** [comment]
I would like to work on this issue if the proposed changes are aligned with the project

**Comment by Vijaykv5** [comment]
@accodes21 I can't see the horizontal scroll bar 
<img width="1439" alt="Screenshot 2023-10-01 at 11 00 26 AM" src="https://github.com/Vijaykv5/Image-Searcher/assets/94985341/5d00c7ab-ff62-4f78-946c-fbdd5754ab03">

**Comment by accodes21** [comment]
It is still visible on the live url here: https://vijaykv-image-searcher.netlify.app/

**Comment by accodes21** [comment]
![Screenshot (386)](https://github.com/Vijaykv5/Image-Searcher/assets/101868279/39cf5803-394f-4ade-bccb-b23a60b4a8b3)
Check the timestamp here
