### ISSUE TITLE
[BUG] Implementing conditional rendering.

### ISSUE THREAD

**Issue by Babunshil** [Vijaykv5/Image-Searcher#54]
**Description**
TypeError: Cannot read properties of undefined (reading 'map').
I want to implement conditional rendering throughout all the mapping components so that the website will break anymore 

![Screenshot (119)](https://github.com/Vijaykv5/Image-Searcher/assets/106283743/43dbd4d0-b96b-425d-b701-a2576d4fb3ba)

Please assign me this issue under HACKTOBERFEST 2023.

**Comment by Vijaykv5** [comment]
@Babunshil This issue has been fixed in the new accepted PR. Please do a git pull for the enrich the new changes
