### ISSUE TITLE
Change the Website Logo and Favicon

### ISSUE THREAD

**Issue by Vijaykv5** [Vijaykv5/Image-Searcher#6]
Add the Website logo and favicon as per the Readme.md file

**Comment by MokshagnaV** [comment]
Hi,
As per the issue stated, should the image present in readme.md need to be placed in the MainSection component and added as a favicon too?

**Comment by MokshagnaV** [comment]
Hi, vijay
1. I suggest you use a prettier linter. As it brings consistency to the code.
2. After going through the code, I think in CSS there are a lot of misuses of extra margins. I think the same design can be developed with less code (by making use of Flex). As it uses negative margins in some places, it became very hard for me to place the icon image on the page in the right place.
3. Can I recode the MainSection component?
   - If yes, please provide any design, or if you want the current design, I will code it.


Thank you

**Comment by MokshagnaV** [comment]
I added the image like this.
Can you please check once?

![image](https://github.com/Vijaykv5/Image-Searcher/assets/92448513/6ac11651-2b12-45da-b431-0ee6cf02b825)

**Comment by Vijaykv5** [comment]
> I added the image like this. Can you please check once?
> 
> ![image](https://user-images.githubusercontent.com/92448513/269348257-6ac11651-2b12-45da-b431-0ee6cf02b825.png)

Hey yeah this looks good but can you do a **git pull** before you work On because now the repo got updated. Also Add a favicon on top too
