### ISSUE TITLE
[BUG] Conditional rendering.

### ISSUE THREAD

**Issue by Babunshil** [Vijaykv5/Image-Searcher#60]
**Description**

Could break while mapping through the images. 
I want to add conditional rendering for all the mapping element so that it doesn't break.
![Screenshot (119)](https://github.com/Vijaykv5/Image-Searcher/assets/106283743/1c3544b0-a85d-4cde-8e0d-37d38cc4ab11)
Please assign me this issue under Hacktoberfest 2023.

**Comment by Vijaykv5** [comment]
@Babunshil Its already solved Its already solved @Babunshil
