### ISSUE TITLE
[FEATURE] Animation while loading images.

### ISSUE THREAD

**Issue by Babunshil** [Vijaykv5/Image-Searcher#62]
**Description**
I want to use framer Motion to make animation while image card are in view

**Comment by Vijaykv5** [comment]
What type of animation you refer to? we already have an ease effect while hovering

please add a video/gif on what animation you're refering to in Framer Motion

**Comment by Babunshil** [comment]
Want to Implement this animation
https://github.com/Vijaykv5/Image-Searcher/assets/106283743/193f7448-056e-4ddb-9772-c65444ad1376

**Comment by Vijaykv5** [comment]
It's actually not needed ..I think current one works fine
