### ISSUE TITLE
[BUG] Improper mobile layout of home page

### ISSUE THREAD

**Issue by nishaaannnt** [Vijaykv5/Image-Searcher#65]
**Description**

the buttons on the home screen are not properly arranged for the mobile view 

**Expected Behavior**

buttons should be stacked properly to be visible accordingly

**Actual Behavior**

buttons are scattered across

**Screenshots (if applicable)**
On mobile view -

![Screenshot 2023-10-01 173934](https://github.com/Vijaykv5/Image-Searcher/assets/100792085/6de38cfa-ca6b-4d68-ac73-9512efd56049)

**Additional Information**

I have created a PR for the same with the issue resolved
Please label  this for #hacktoberfest2023 #hacktoberfest

**Comment by Vijaykv5** [comment]
@nishaaannnt the issue has been already updated in #66  and has being fixed 

Also Please work on these issues only once you're assigned

**Comment by nishaaannnt** [comment]
@Vijaykv5 oh sorry for that i did'nt knew that. Thank you for informing !
