### ISSUE TITLE
bug: API key configuration

### ISSUE THREAD

**Issue by MokshagnaV** [Vijaykv5/Image-Searcher#7]
The API key is taking from ```PARCEL_API_KEY``` variable rather than ```REACT_APP_UNSPLASH_API_KEY``` variable. 
The app is not working with that configuration

If this change is made, the app is running fine locally.
![image](https://github.com/Vijaykv5/Image-Searcher/assets/92448513/d0a02cfc-a882-4835-83a1-5bbb3e4d3846)

Why the  ```PARCEL_API_KEY``` is used, not ```REACT_APP_UNSPLASH_API_KEY```? 
Is it for production? 
Or the above is required?

**Comment by Vijaykv5** [comment]
Yeah I guess PARCEL_API_KEY is fine as in this project I'm using parcel as a bundlar rather than webpack. So It should also work fine locally

**Comment by Vijaykv5** [comment]
I rechecked and Its working fine for me ... If you would please work on this issue #6 @MokshagnaV
